<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<div class="navbar-header">
    <?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span
            class="sr-only"> <?php /* @escapeNotVerified */ echo __('Toggle Nav') ?> </span> <span class="icon-bar"> </span> <span
            class="icon-bar"> </span> <span class="icon-bar"> </span></button>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-cart"><i
            class="fa fa-shopping-cart colorWhite"> </i> <span
            class="cartRespons colorWhite"> Cart ($210.00) </span></button>
    <?php if ($block->isHomePage()): ?>
    <strong class="navbar-brand">
    <?php else: ?>
        <a class="navbar-brand" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
    <?php endif ?>
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>" alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
            <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?> <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?> />
    <?php if ($block->isHomePage()): ?>
        </strong>
    <?php else: ?>
        </a>
    <?php endif ?>
    <!-- this part for mobile -->
    <div class="search-box pull-right hidden-lg hidden-md hidden-sm">
        <div class="input-group">
            <button class="btn btn-nobg getFullSearch" type="button"><i class="fa fa-search"> </i></button>
        </div>
        <!-- /input-group -->
    </div>
</div>
