<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare  = true;
    $showCart     = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description  = false;
    ?>
    <div class="container main-container <?php echo $mode; ?>">
        <div class="row featuredPostContainer globalPadding style2">
            <?php if ($title): ?>
                <h3 class="section-title style2 text-center"><span><?php echo $title; ?></span></h3>
            <?php endif ?>
            <div id="productslider" class="owl-carousel owl-theme">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <div class="item">
                        <div class="product">
                            <?php if ($showWishlist || $showCompare): ?>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                        <a href="#" data-toggle="tooltip" data-original-title="Add to Wishlist"
                                           data-placement="left"
                                           data-post='<?php echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist add-fav tooltipHere" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
                                            <i class="glyphicon glyphicon-heart"> </i>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#" class="action tocompare add-fav tooltipHere"
                                           data-placement="left"
                                           data-toggle="tooltip" data-original-title="Add to Wishlist"
                                           data-post='<?php
                                           echo $compareHelper->getPostDataParams($_item); ?>'
                                           title="<?php
                                           echo __('Add to Compare') ?>">
                                            <i class="glyphicon glyphicon-heart"> </i>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <div class="image">
                                <div class="quickview">
                                    <a title="Quick View" class="btn btn-xs  btn-quickview"
                                       data-target="#product-details-modal" data-toggle="modal"> Quick View </a>
                                </div>
                                <a href="<?php echo $block->getProductUrl($_item) ?>">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>

                                <div class="promotion"><span class="new-product"> NEW</span>
                                    <span class="discount">15% OFF</span>
                                </div>
                            </div>
                            <div class="description">
                                <h4>
                                    <a href="<?php echo $block->getProductUrl($_item) ?>"><?php echo $block->escapeHtml($_item->getName()) ?></a>
                                </h4>

                                <p><?php echo $block->escapeHtml($_item->getDescription()) ?></p>
                            </div>
                            <div class="price">
                                <span><?php echo $block->getProductPriceHtml($_item, $type); ?></span>
                            </div>
                            <div class="action-control">
                                <?php if ($showCart): ?>
                                    <span class="add2cart">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                            <button class="action tocart primary btn btn-primary" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary btn btn-primary"
                                                    data-post='<?php
                                                    echo $postData; ?>'
                                                    type="button" title="<?php
                                            echo __('Add to Cart') ?>">
                                                <i class="glyphicon glyphicon-shopping-cart"></i><?php
                                                echo __('Add to Cart') ?>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_item->getIsSalable()): ?>
                                            <div class="stock available"><span><?php
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    </span>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    </div>
<?php endif; ?>
